### PR TITLE
Yesod backend

### PR DESCRIPTION
**Pull request by bsima**
Rewriting the backend to use Haskell's Yesod framework. This gon' be good.

### CODE REVIEW

**Comment by Reticentman** [comment]
@bsima Awesome!

**Comment by bsima** [comment]
Problem is:

- with [lts-6.10][] I get this "`cannot satisfy --package-key main`" problem. The
  solution seems to be to [upgrade to ghc-8.0][1] which means moving to stackage
  [lts-7.24][] or [lts-9.2][].
- with [lts-7.24][] imports are fubar'd. I get a cyclical import/export problem with
  the `src/Import.hs` file.
- trying with [lts-9.2][] next...

[1]: https://github.com/yesodweb/yesod/issues/979#issuecomment-253946547

[lts-6.10]: https://www.stackage.org/lts-6.10
[lts-7.24]: https://www.stackage.org/lts-7.24
[lts-9.2]: https://www.stackage.org/lts-9.2

**Comment by bsima** [comment]
Yay finally the build passed! Two things left to do:

- [ ] make sure the Elm app is wired up to the Yesod backend
- [ ] change Heroku deploy settings to work for Haskell

**Comment by bsima** [comment]
@Reticentman this is ready for review now that it is building and deploying properly.

Next steps are to start filling out the backend functionality with a database and stuff. I will be working on that mostly, and you can work on the Elm frontend as I build out the backend with data for you to use

**Comment by Reticentman** [comment]
Great work!

**Pull request merged**
